apiVersion: v1
kind: Pod
metadata:
  name: feast-california-fetcher
  labels:
    app: feast-fetcher
spec:
  containers:
  - name: feast-fetcher
    image: feast-california:latest
    imagePullPolicy: Never
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "minio"
    - name: AWS_SECRET_ACCESS_KEY
      value: "minio123"
    - name: FEAST_S3_ENDPOINT_URL
      value: "http://minio-service.kubeflow.svc.cluster.local:9000"
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  restartPolicy: Never 